### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by A-Manning** [sean0921/debian-gnome-terminal-transparency#1]
Would it be possible to build and release for armv7? Especially important for Raspbian users

**Comment by sean0921** [comment]
I’ll try it, it seems possible.

A L Manning ***@***.***>於 2021年7月4日 週日，上午2:06寫道：

**Comment by sean0921** [comment]
@A-Manning  `armhf` version of package files were uploaded, please help to check if there's any problem for installing it, thx.

**Comment by sean0921** [comment]
updated here:
<https://github.com/sean0921/debian-gnome-terminal-transparency/releases/tag/3.38.3-1sean01>

**Comment by A-Manning** [comment]
Thanks so much!
Unfortunately I was unable to install via the packages provided, due to a dependency on `libvte-2.91-0 (>= 0.62.1)`, which is unavailable in debian stable.

```
$ sudo dpkg -i ./gnome-terminal_3.38.3-1sean01_armhf.deb ./gnome-terminal-dbgsym_3.38.3-1sean01_armhf.deb
```
```
(Reading database ... 167414 files and directories currently installed.)
Preparing to unpack .../gnome-terminal_3.38.3-1sean01_armhf.deb ...
Unpacking gnome-terminal (3.38.3-1sean01) over (3.30.2-2) ...
Selecting previously unselected package gnome-terminal-dbgsym.
Preparing to unpack .../gnome-terminal-dbgsym_3.38.3-1sean01_armhf.deb ...
Unpacking gnome-terminal-dbgsym (3.38.3-1sean01) ...
dpkg: dependency problems prevent configuration of gnome-terminal:
 gnome-terminal depends on gnome-terminal-data (>= 3.38); however:
  Version of gnome-terminal-data on system is 3.30.2-2.
 gnome-terminal depends on libvte-2.91-0 (>= 0.62.1); however:
  Version of libvte-2.91-0:armhf on system is 0.54.2-2.

dpkg: error processing package gnome-terminal (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gnome-terminal-dbgsym:
 gnome-terminal-dbgsym depends on gnome-terminal (= 3.38.3-1sean01); however:
  Package gnome-terminal is not configured yet.

dpkg: error processing package gnome-terminal-dbgsym (--install):
 dependency problems - leaving unconfigured
```

**Comment by sean0921** [comment]
Hi, Because version 3.38.3 is made for Debian Bullseye (11, testing), later I will build armhf verion 3.30.x for Debian(Raspbian) Buster (10,stable) :)

**Comment by sean0921** [comment]
After I uploaded that package you need, the correct command to install is:
```bash
apt install ./gnome-terminal_3.30.2-2sean01_armhf.deb ./gnome-terminal-data_3.30.2-2sean01_all.deb
```

**Comment by sean0921** [comment]
Link for download:
https://github.com/sean0921/debian-gnome-terminal-transparency/releases/tag/debian%2F3.30.2-2sean01

**Comment by A-Manning** [comment]
Thank you! Works perfectly :+1:
